# Generated by Django 5.0.1 on 2024-01-02 09:53

import api.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('location', models.CharField(max_length=200, null=True)),
                ('jobType', models.CharField(choices=[('Training', 'Training'), ('Internship', 'Internship'), ('FullTime', 'Fulltime'), ('PartTime', 'Parttime')], default='Training', max_length=10)),
                ('qualification', models.CharField(choices=[('Any', 'Any'), ('SSC or equivalent', 'Ssc'), ('HSC or equivalent', 'Hsc'), ('Undergraduate', 'Undergraduate'), ('Postgraduate', 'Postgraduate')], default='Any', max_length=25)),
                ('salary', models.IntegerField(default=0)),
                ('openings', models.IntegerField(default=1)),
                ('createdAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('expiresAt', models.DateTimeField(null=True, verbose_name=api.models.expireDate)),
                ('company', models.CharField(max_length=30, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
