# Generated by Django 5.0.1 on 2024-01-17 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_job_description_job_email_alter_job_openings_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='company',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='Company',
        ),
    ]
