# Generated by Django 5.0.1 on 2024-01-20 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_job_description_job_email_alter_job_openings_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='user',
        ),
    ]
