# Generated by Django 5.0.1 on 2024-01-30 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_job_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='status',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='jobType',
            field=models.CharField(choices=[('training', 'Training'), ('internship', 'Internship'), ('fullTime', 'Fulltime'), ('partTime', 'Parttime')], default='training', max_length=10),
        ),
        migrations.AlterField(
            model_name='job',
            name='qualification',
            field=models.CharField(choices=[('any', 'Any'), ('ssc', 'Ssc'), ('hsc', 'Hsc'), ('undergraduate', 'Undergraduate'), ('postgraduate', 'Postgraduate')], default='any', max_length=25),
        ),
    ]
