# Generated by Django 5.0.1 on 2024-02-03 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_job_status_alter_job_jobtype_alter_job_qualification'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='phone',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='jobType',
            field=models.CharField(choices=[('training', 'Training'), ('internship', 'Internship'), ('fulltime', 'Fulltime'), ('parttime', 'Parttime')], default='training', max_length=10),
        ),
    ]
