# Generated by Django 5.0.1 on 2024-02-13 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_job_salary3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='salary3',
        ),
    ]
