#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

npm test

echo 'Testing and building project before comitting'

npm run check-types ||
(
    echo 'Failed type check'
    false;
)

npm run build ||
(
    echo 'Build failed'
    false;
)

echo 'No problems found'