import { ThemeProvider } from "@/components/ui/theme";
import { Container } from "@radix-ui/themes";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "./navBar";
import Footer from "./components/footer";
import Providers from "./Providers";
import { Toaster } from "@/components/ui/toaster"

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <Providers>
      <html lang="en">
        <body>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <NavBar />
            <main className="p-24">
              <Container>{children}</Container>
            </main>
            <Toaster />
            <Footer />
          </ThemeProvider>
        </body>
      </html>
    </Providers>
  );
}
