name: Docker Publish


on:
    push:
        branches:
            - main
            - development

env:
    REGISTRY: docker.io
    IMAGE_NAME: rahman184/private
    TAG: project-v1.0

jobs:
    test:
        runs-on: ubuntu-latest
    
        steps:
                - name: Checkout Code
                  uses: actions/checkout@v4

