name: Docker Publish


on:
    push:
        branches:
            - main
            - development

env:
    REGISTRY: docker.io
    IMAGE_NAME: rahman184/private
    TAG: project-v1.0

jobs:
    test:
        runs-on: ubuntu-latest
    
        steps:
                - name: Checkout Code
                  uses: actions/checkout@v4

                - name: Setup Python
                  uses: actions/setup-python@v5
                  with:
                    python-version: '3.12'

                - name: Install Dependencies
                  run: |
                      cd backend
                      python -m pip install --upgrade pip
                      pip install poetry
                      poetry config virtualenvs.create false
                      poetry install --no-dev

                - name: Run Tests
                  run: |
                     cd backend
                     python manage.py test